spring:
  main:
    banner-mode: off
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: 123123
  thymeleaf:
    cache: true
    encoding: UTF-8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启下划线驼峰转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启日志
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
server:
  port: 8888
