
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123123
  data:
    redis:
      host: 192.168.2.131
      port: 6379
      password: 123123
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000
mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: blog_
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml


